name:                peml
version:             0.1.0.0
github:              "orchestracities/peml"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Programmable, type-safe, human-readable data description language.
category:            Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/orchestracities/peml#readme>

dependencies:
- base >= 4.7 && < 5
- base-unicode-symbols >= 0.2 && < 1
- aeson >= 1.4 && < 2
- aeson-pretty >= 0.8 && < 1
- bytestring >= 0.10 && < 1
- containers >= 0.6 && < 1
- text >= 1.2 && < 2
- HsYAML >= 0.2 && < 1

library:
  source-dirs: src

# executables:
#   peml-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - peml

tests:
  peml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - peml
